CREATE TABLESPACE LEANDRO_01 DATAFILE SIZE 10M AUTOEXTEND ON NEXT 10M ;

-- roles
CREATE ROLE RO_LEANDRO ;

-- logins
CREATE USER LEANDRO IDENTIFIED BY LEANDRO DEFAULT TABLESPACE LEANDRO_01 ;

-- grant
GRANT CREATE TABLE TO LEANDRO ;


ALTER USER LEANDRO QUOTA UNLIMITED ON LEANDRO_01 ;


-- permissao para conectar 
GRANT CONNECT, RESOURCE TO LEANDRO;


